Add compatibility for audio objects
bondjimbond/islandora_video_embed pull request #4
Opened 2018-12-04 19:15 UTC by IAMlKeno

2018-12-04 19:26 UTC, IAMlKeno commented
### Description of changes:
- Added functionality to allow embed code to be created for audio objects as well.
- Applied coding standards
- Update descriptions and comments to reflect added functionality

2018-12-04 19:46 UTC, bondjimbond requested changes
Thanks for the contribution! I guess I'll have to think about changing the name of the module after this is merged.

Seems to work! Just some tiny tweaks to the audio section, and it will be good to go.

2018-12-04 19:46 UTC, bondjimbond commented on islandora_video_embed.module
> +    $audio_url = $base_url . '/islandora/object/' . $pid . '/datastream/' . $dsid . '/download/file.mp4';
should be file.mp3

2018-12-04 19:46 UTC, bondjimbond commented on islandora_video_embed.module
> +      &lt;source src="' . $audio_url . '" type="audio/mp4"&gt; <br/>
mimetype should be audio/mepg

2018-12-04 20:47 UTC, IAMlKeno commented on islandora_video_embed.module
> +    $audio_url = $base_url . '/islandora/object/' . $pid . '/datastream/' . $dsid . '/download/file.mp4';
updated!

2018-12-04 20:48 UTC, IAMlKeno commented on islandora_video_embed.module
> +      &lt;source src="' . $audio_url . '" type="audio/mp4"&gt; <br/>
updated!

2018-12-04 20:48 UTC, IAMlKeno commented
Happy to contribute

2018-12-05 14:41 UTC, bondjimbond approved these changes

2018-12-05 14:44 UTC, merged

2018-12-06 15:08 UTC, bondjimbond commented
@IAMlKeno Just FYI to keep your fork up to date... I had to remove the `null` in line 65, as it caused warnings.